Code generation for databases and quartz
AxonIQ/initializr pull request #53
Opened 2021-12-09 13:19 UTC by schananas

Adds code generation for:

H2 DB - properties
Postgresql DB - properities and docker image
Flyway - initial axon scripts setup
Liquibase - initial axon scripts setup
Quartz - added Quartz as dependecy option, application properties and flyway/liquibase scripts

2021-12-10 14:30 UTC, smcvb requested changes

2021-12-10 14:30 UTC, smcvb commented on initializr-be/src/main/resources/configuration/axon-framework/quartz/application.properties
> +org.quartz.jobStore.tablePrefix=QRTZ_
Nit: FYI, GitHub's complaining about the end of file for several of the `.properties` additions.

2021-12-10 14:36 UTC, schananas commented on initializr-be/src/main/java/io/axoniq/initializr/FileContributor.java
> +public abstract class FileContributor {
FileManager? :)

2021-12-10 16:18 UTC, schananas commented on initializr-be/src/main/resources/configuration/axon-framework/flyway/create_axon_framework_related_tables_baseline.sql
> +    token oid,
@lfgcampos do you know this one?

2021-12-10 16:19 UTC, schananas commented on initializr-be/src/main/resources/configuration/axon-framework/quartz/application.properties
> +org.quartz.jobStore.tablePrefix=QRTZ_
I didn't pick up whats the problem here?

2022-01-20 11:07 UTC, lfgcampos commented on initializr-be/src/main/resources/configuration/axon-framework/flyway/create_axon_framework_related_tables_baseline.sql
> +    token oid,
Since we didn't want to map this option for every DB at this point in time, we went for a small comment on the top of the files stating it was tested agains PostgreSQL only and that the script should be adapted for others DB.

As a matter of fact, this is the final mapping we worked out (for future work):
```
PostgreSQL Driver   	-> BYTEA
Oracle Driver		-> BLOB
MySQL Driver		-> BLOB
MS SQL Server Driver	-> VARBINARY
MariaDB Driver		-> BINARY
HyperSQL Database	-> VARBINARY
H2 Database		-> BINARY
IBM DB2 Driver		-> BLOB
```

2022-01-24 10:55 UTC, smcvb commented on initializr-be/src/main/resources/configuration/axon-framework/quartz/application.properties
> +org.quartz.jobStore.tablePrefix=QRTZ_
This is the point I'm referring too:
![newline](https://user-images.githubusercontent.com/4687743/150770311-c296b002-daab-4852-8cf0-62e5f645fb75.jpg)

2022-01-24 10:56 UTC, smcvb commented on initializr-be/src/main/resources/configuration/axon-framework/flyway/create_axon_framework_related_tables_baseline.sql
> +    token oid,
Aight, I agree with Lucas here. As long as it's clear to the user that these are based on PostgreSQL, we should be covered. I do think it's good to put something on the backlog for switching between different dbs.

2022-01-24 12:32 UTC, smcvb approved these changes
My concerns have been addressed, hence approving.

2022-01-24 17:36 UTC, merged